<a href="https://colab.research.google.com/github/RICHAR-SL/Practica-Calificada1/blob/main/Practica_Calificada_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Ejercicio1***:

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Crea un vector de numeros enteros del 1 al 20
vector1=np.arange(1,21)
print(vector1)
print('\n\n')
#Crea una matriz de 3 x 3 con valores aleatorios entre 0 y 1
matriz1=np.random.rand(3,3)
print(matriz1)
print('\n\n')
#Redimenciona una matriz de 4x4 a una matriz de 2x8
print('\n\n')
matriz2=np.random.rand(4,4)
print(matriz2)

print('\n')
print('Matriz redimencionado')
matriz_redimencionado=matriz2.reshape(2,8)
print(matriz_redimencionado)

#Crea un array de 10 numeros equidistantes entre 0 y 1
print('\n\n')
array_equidistante= np.linspace(0,1,10)
print(array_equidistante)

#Concatena don vectores verticales y horizontales
vect1_1=([1,23,4,5,6])
vect2_2=([8,9,7,54,4])
concatenado_vertical=np.vstack((vect1_1,vect2_2))
concatenado_horizontal=np.hstack((vect1_1,vect2_2))
print("Vertical")
print(concatenado_vertical)
print("\n\n")
print("Horizontal")
print(concatenado_horizontal)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]



[[0.45919857 0.32611781 0.49421526]
 [0.5973781  0.30347436 0.56379368]
 [0.99339995 0.77882096 0.53306462]]






[[0.76066453 0.66153617 0.45066153 0.01950015]
 [0.51860781 0.40802249 0.28989435 0.56975041]
 [0.76804241 0.29296425 0.98657576 0.31243409]
 [0.10292499 0.4102454  0.58068295 0.92634846]]


Matriz redimencionado
[[0.76066453 0.66153617 0.45066153 0.01950015 0.51860781 0.40802249
  0.28989435 0.56975041]
 [0.76804241 0.29296425 0.98657576 0.31243409 0.10292499 0.4102454
  0.58068295 0.92634846]]



[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Vertical
[[ 1 23  4  5  6]
 [ 8  9  7 54  4]]



Horizontal
[ 1 23  4  5  6  8  9  7 54  4]


In [ ]:

vector1=np.array([1,2,3,4,5])
vector2=np.array([6,7,8,9,10])
#calcula la suma, resta, multiplicacion y division de dos vectores
sumade=vector1+vector2
restade=vector2-vector1
multide=vector1*vector2
divisionde=vector2/vector1
print("suma")
print(sumade)
print("resta")
print(restade)
print("multiplicacion")
print(multide)
print("division")
print(divisionde)
#calcula la media, mediana y desviacion de un vector
print("media de vector1")
media=np.mean(vector1)
print(media)
print("mediana de vector1")
mediana=np.median(vector1)
print(mediana)
print("desviacion de vector1")
desviacion=np.std(vector1)
print(desviacion)

#normaliza un vector dividiendo cada valor por el valor maximo

vector_normal=vector2
print("normaliza un vector dividiendo cada valor por el valor maximo")
vector_normal=vector_normal / np.max(vector2)
print(vector_normal)
#Encuentra el indice del valor maximo y minimo de un vector
print("Encuentra el indice del valor maximo y minimo de un vector1")

vectormax=np.argmax(vector1)
vectormin=np.argmin(vector1)
print("maximo",vectormax)
print("minimo", vectormin)


#Realiza una multiplicacion matricial entre dos matrices de 3 x 3

matrixz1=np.array([[1,2,2],[3,4,7],[5,6,9]])

matrixz2=np.array([[11,12,1],[9,10,11],[7,8,7]])
matriz_mutiplicacido=np.dot(matrixz1,matrixz2)
print(matriz_mutiplicacido)

suma
[ 7  9 11 13 15]
resta
[5 5 5 5 5]
multiplicacion
[ 6 14 24 36 50]
division
[6.         3.5        2.66666667 2.25       2.        ]
media de vector1
3.0
mediana de vector1
3.0
desviacion de vector1
1.4142135623730951
normaliza un vector dividiendo cada valor por el valor maximo
[0.6 0.7 0.8 0.9 1. ]
Encuentra el indice del valor maximo y minimo de un vector1
maximo 4
minimo 0
[[ 43  48  37]
 [118 132  96]
 [172 192 134]]


In [47]:

vectortotal=np.array([-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,30,60,80,90])

print("Selecciona los elementos pares de un vector de números enteros")

pares = vectortotal[vectortotal % 2 == 0]
print("Elementos pares:", pares)

print("\nFiltra los valores mayores que 5 en un vector")
mayores_5 = vectortotal[vectortotal > 5]
print("Valores mayores que 5:", mayores_5)

print("\nFiltra los valores iguales a cero")
iguales_cero = vectortotal[vectortotal == 0]
print("Valores iguales a 0:", iguales_cero)

print("\nFiltra los valores negativos")
negativos = vectortotal[vectortotal < 0]
print("Valores negativos:", negativos)

print("\nAplica la media a los valores mayores de 50")
mayores_50 = vectortotal[vectortotal > 50]
media_mayores_50 = np.mean(mayores_50)
if mayores_50.size > 0 :
  print(media_mayores_50)



Selecciona los elementos pares de un vector de números enteros
Elementos pares: [-4 -2  0  2  4  6  8 10 30 60 80 90]

Filtra los valores mayores que 5 en un vector
Valores mayores que 5: [ 6  7  8  9 10 30 60 80 90]

Filtra los valores iguales a cero
Valores iguales a 0: [0]

Filtra los valores negativos
Valores negativos: [-5 -4 -3 -2 -1]

Aplica la media a los valores mayores de 50
76.66666666666667


ejr4


In [ ]:
vectortotal=np.array([-1,0,1,2,3,4,5,6,7,8])
print("crea un vector de 10 elementos y reemplaza todos los valores mayores que 5 con 0")


print("Combina dos vectores booleano utilizando las operaciones and y or")


print("cuenta la cantidad de valores en un vector  que son multiples de 3")


print("encuentra los indices de los elementos no nulos en un vector (np.nonzero)")


print("comprueba si todos los elementos en un array son mayores que un valor especifico digitado por el usuario")





